defaults: &defaults
  docker:
    - image: circleci/node:12.13.1
  working_directory: ~/uitest

aliases:
  - &save_dependencies
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
  - &restore_dependencies
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}
      - v1-dependencies-

version: 2.1

jobs:
  install_dependencies:
    steps:
      - restore_cache: *restore_dependencies
      - run: sudo npm install -g yarn@latest
      - run: yarn install
      - save_cache: *save_dependencies

  build_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/uitest
      - run: yarn build
      - persist_to_workspace:
          root: ~/uitest
          paths:
            - build
            - lib
            - package.json
      - store_artifacts:
          path: ~/test-ui/lib
          destination: production-dist

  publish_package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/uitest
      - run: npx semantic-release
      - run: echo "//npm.pkg.github.com/:_authToken=$GH_TOKEN" > ~/.npmrc
      - run: npm publish

workflows:
  version: 2.1

  development:
    jobs:
      # - test_jest

  publish:
    jobs:
      - install_dependencies
      - build_production:
          requires:
            - install_dependencies
      - publish_package:
          requires:
            - build_production
