defaults: &defaults
  docker:
    - image: circleci/node:12.13.1
  working_directory: ~/medwing-ui

aliases:
  - &save_dependencies
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
  - &restore_dependencies
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}
      - v1-dependencies-

version: 2.1

commands:
  authenticate_npm_registry:
    steps:
      - run:
          name: Authenticate with registry
          command: echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" > ~/.npmrc
  install_dependencies:
    steps:
      - restore_cache: *restore_dependencies
      - run: |
          if [ ! -d "node_modules" ] || [ $(git diff --name-only HEAD~1 HEAD | grep -c "yarn.lock") == 1 ]; then
            sudo npm install -g yarn@latest
            yarn install
          fi
      - save_cache: *save_dependencies

  build_production:
    steps:
      - checkout
      - install_dependencies
      - run: yarn build
      - persist_to_workspace:
          root: ~/medwing-ui
          paths:
            - build
            - lib
            - package.json
  npm_publish:
    steps:
      - run:
          name: Publish package
          command: npm publish

jobs:
  test_jest:
    <<: *defaults
    steps:
      - checkout
      - install_dependencies
      - build_production

  build_production:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/medwing-ui
      - build_production
      - store_artifacts:
          path: ~/test-ui/lib
          destination: production-dist
  publish_package:
    <<: *defaults
    steps:
      - attach_workspace:
          at: ~/medwing-ui
      - authenticate_npm_registry
      - npm_publish
workflows:
  version: 2.1

  development:
    jobs:
      - test_jest

  deployment_production:
    jobs:
      - build_production
      - publish_package:
          requires:
            - build_production
          filters:
            tags:
              only: /^v.*/
            branches:
              ignore: /.*/
