defaults: &defaults
  docker:
    - image: circleci/node:12.13.1
  working_directory: ~/uitest

aliases:
  - &save_dependencies
    key: v1-dependencies-{{ checksum "yarn.lock" }}
    paths:
      - node_modules
  - &restore_dependencies
    keys:
      - v1-dependencies-{{ checksum "yarn.lock" }}
      - v1-dependencies-

version: 2.1

jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_dependencies
      - run: sudo npm install -g yarn@latest
      - run: yarn install
      - save_cache: *save_dependencies

  test_lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_dependencies
      - run: yarn run test:lint

  build_production:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_dependencies
      - run: yarn build
      - persist_to_workspace:
          root: ~/uitest
          paths: .
      - store_artifacts:
          path: ~/uitest/build

  publish_package:
    <<: *defaults
    steps:
      - checkout
      - restore_cache: *restore_dependencies
      - run: echo "//npm.pkg.github.com/:_authToken=$GH_TOKEN" > ~/uitest/.npmrc
      - run: npx semantic-release

workflows:
  version: 2.1

  development:
    jobs:
      - install_dependencies
      - test_lint:
          requires:
            - install_dependencies
            
  publish:
    jobs:
      - install_dependencies:
          filters:
            branches:
              only:
                - master
      - build_production:
          requires:
            - install_dependencies
      - publish_package:
          requires:
            - build_production
